// const { Middleware } = require('swagger-express-middleware');
import http from 'http'
import fs from 'fs'
import path from 'path'
import swaggerUI, { JsonObject } from 'swagger-ui-express'
import yaml from 'js-yaml'
import express, { Express, NextFunction, Request, Response } from 'express'
import cors from 'cors'
import cookieParser from 'cookie-parser'
import bodyParser from 'body-parser'
import * as OpenApiValidator from 'express-openapi-validator'
import logger from './logger'
import config from './config'
import { ResponseError } from './interfaces'
import { CODE_UNKNOWN } from './constants'

function formatResponseError(err: Error) {}

class ExpressServer {
    port: number
    app: Express
    openApiPath: string
    schema: JsonObject
    server: unknown // TODO: ?

    constructor(port: number, openApiYaml: string) {
        this.port = port
        this.app = express()
        this.openApiPath = openApiYaml
        try {
            this.schema = yaml.load(
                fs.readFileSync(openApiYaml, 'utf8'),
            ) as JsonObject
        } catch (error) {
            logger.error({
                message: 'failed to convert openApiYaml to JsonSchema',
                error,
            })
        }

        this.setupMiddleware()
    }

    setupMiddleware() {
        // this.setupAllowedMedia();
        this.app.use(cors())
        this.app.use(bodyParser.json({ limit: '14MB' }))
        this.app.use(express.json())
        this.app.use(express.urlencoded({ extended: false }))
        this.app.use(cookieParser())
        //
        // View the openapi document in a visual interface. Should be able to test from this page
        //
        this.app.use('/api-doc', swaggerUI.serve, swaggerUI.setup(this.schema))
        //
        // Send the openapi document *AS GENERATED BY THE GENERATOR*
        //
        this.app.get('/openapi', (req, res) =>
            res.sendFile(path.join(__dirname, 'api', 'openapi.yaml')),
        )

        this.app.use(this.openapiValidator())
        this.app.use(this.errorHandleMiddleawre)
    }

    /**
     * validate request and response data structure
     */
    openapiValidator() {
        return OpenApiValidator.middleware({
            apiSpec: this.openApiPath,
            operationHandlers: path.join(__dirname),
            fileUploader: { dest: config.FILE_UPLOAD_PATH },
            // validateResponses: true, // <-- to validate responses
        })
    }

    /**
     * 错误处理，大部分的错误都应该汇总到这里进行处理
     */
    errorHandleMiddleawre(
        err,
        req: Request,
        res: Response,
        next: NextFunction,
    ) {
        const status = err.status || 500

        if (status === 500) {
            logger.error({ message: 'global handle error', error: err })
        }

        const responseData: ResponseError = {
            code: err.code || CODE_UNKNOWN,
            message: `${err.name || 'Error'}: ${
                err.message || 'unknown error'
            }`,
            data: err.errors || [],
        }

        res.status(status).json(responseData)
    }

    launch() {
        http.createServer(this.app).listen(this.port)
        logger.info(`Listening on port ${this.port}`)
    }

    async close() {
        // TODO: server 哪里来?
        if (this.server !== undefined) {
            // @ts-ignore
            await this.server.close()
            logger.info(`Server on port ${this.port} shut down`)
        }
    }
}

export default ExpressServer
